import type { NextPage } from 'next'
import Head from 'next/head'
import styles from 'styles/Home.module.css'
import TextInput from 'component/TextInput'
import Button from 'component/Button';
const Login: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>OutreachApp</title>
        <meta name="description" content="Generated by create OutreachApp" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.titleName}>OutreachApp</div>
        <div className={styles.grid}>
         <TextInput placeholder='Email or Phone Number'/>
         <TextInput placeholder='Password'/>
          <Button text='Login' link='/login'/>
        </div>
      </main>
    </div>
  )
}

export default Login
