import React, {
  forwardRef,
} from 'react'
import Head from 'next/head'

export interface HeadTagProps  {
  style?: object
  text?: string
  placeholder?:string
}
const HeadTag: React.FC<HeadTagProps> = forwardRef((props, _HeadTagRef) => {
  return (
    <Head>
        <title>OutreachApp</title>
        <meta name="description" content="Generated by create OutreachApp" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet"></link>
    </Head>
  )
})

export default HeadTag
